name: "Henry Hadlow"
description: "Henry is a designer. This is his portfolio."

url: "http://localhost:4000"
permalink: /:categories/:title

paginate: 10

encoding: UTF8-MAC

sass:
  sass_dir: static/_scss
